const en = {
  connectTitle: "Connect to your panel",
  connectBody: "Open “Teach from your browser” in the panel, copy the code it shows and paste it here.",
  panelLabel: "Panel address",
  codeLabel: "Pairing code",
  codePlaceholder: "ABCD-EFGH",
  connect: "Connect",
  connecting: "Connecting…",
  whereIsCode: "Where do I find the code?",
  signedInAs: (name: string) => `Connected as ${name}`,
  pickTitle: "Who are you teaching?",
  noAgents: "You do not have an understudy yet. Create one in the panel first.",
  online: "computer on",
  offline: "computer off",
  voice: "Record my voice",
  voiceHint: "Explain out loud why you do each step. It is how your understudy learns the reasons.",
  start: "Start recording",
  starting: "Starting…",
  privacy: "Only tabs in this browser are recorded, and only while recording is on. Passwords, card numbers and one-time codes are never captured.",
  recordingFor: (name: string) => `Teaching ${name}`,
  recording: "Recording",
  paused: "Paused",
  pause: "Pause",
  resume: "Resume",
  stop: "I'm done",
  discard: "Discard",
  steps: (n: number) => (n === 1 ? "1 step so far" : `${n} steps so far`),
  doTask: "Do the task in your tabs the way you always do, and talk while you do it.",
  listening: "Listening",
  silent: "Voice off",
  finishing: "Sending what you did…",
  processing: (name: string) => `${name} is writing the task down`,
  processingHint: "This takes a minute or two. You can close this window.",
  done: "The task is ready",
  doneHint: "Review it in the panel and turn it on.",
  review: "Review the task",
  failed: "That did not work",
  again: "Teach again",
  openPanel: "Open panel",
  disconnect: "Disconnect",
  micTitle: "Let me hear you",
  micBody: "Chrome will ask to use your microphone. Your voice is only recorded while you are teaching, and it is deleted after it is turned into text.",
  micAllow: "Allow microphone",
  micDone: "Microphone ready. Go back to the extension and press Start recording.",
  micBlocked: "The microphone is blocked. Click the icon on the right of the address bar, allow the microphone, then try again.",
  micNeeded: "Allow the microphone first. A tab opened to ask for it.",
  pillRecording: (name: string) => `Recording for ${name}`,
  pillPaused: (name: string) => `Paused · teaching ${name}`,
  pillShow: "Show recording controls",
  pillHide: "Hide recording controls",
  errors: {
    invalid_code: "That code did not work. Codes last 10 minutes: get a new one in the panel.",
    invalid_server: "That panel address does not look right.",
    offline: "Could not reach the panel. Check the address and your connection.",
    unauthorized: "This browser was disconnected. Connect again.",
    agent_not_found: "That understudy is not yours or no longer exists.",
    mic_denied: "The microphone is blocked. Allow it, or turn off “Record my voice”.",
    mic_missing: "No microphone found. Plug one in, or turn off “Record my voice”.",
    mic_failed: "The microphone did not start. Try again, or turn off “Record my voice”.",
    audio_upload_failed: "Part of your voice did not reach the panel. The steps were kept.",
    recipe_failed: "Your understudy could not turn this into a task. Check the panel for the reason.",
    too_many_requests: "Too many tries. Wait a moment and try again.",
    busy: "A recording is already running.",
    unknown: "Something went wrong. Try again.",
  } as Record<string, string>,
};

const ptBR: typeof en = {
  connectTitle: "Conecte ao seu painel",
  connectBody: "Abra “Ensinar pelo navegador” no painel, copie o código que aparece e cole aqui.",
  panelLabel: "Endereço do painel",
  codeLabel: "Código de pareamento",
  codePlaceholder: "ABCD-EFGH",
  connect: "Conectar",
  connecting: "Conectando…",
  whereIsCode: "Onde acho o código?",
  signedInAs: (name: string) => `Conectado como ${name}`,
  pickTitle: "Quem você vai ensinar?",
  noAgents: "Você ainda não tem um agente. Crie um no painel primeiro.",
  online: "computador ligado",
  offline: "computador desligado",
  voice: "Gravar minha voz",
  voiceHint: "Explique em voz alta por que você faz cada passo. É assim que seu agente aprende os motivos.",
  start: "Começar a gravar",
  starting: "Começando…",
  privacy: "Só as abas deste navegador são gravadas, e só enquanto a gravação está ligada. Senhas, números de cartão e códigos de uso único nunca são capturados.",
  recordingFor: (name: string) => `Ensinando ${name}`,
  recording: "Gravando",
  paused: "Pausado",
  pause: "Pausar",
  resume: "Continuar",
  stop: "Terminei",
  discard: "Descartar",
  steps: (n: number) => (n === 1 ? "1 passo até agora" : `${n} passos até agora`),
  doTask: "Faça a tarefa nas suas abas do jeito de sempre e vá falando enquanto faz.",
  listening: "Ouvindo",
  silent: "Voz desligada",
  finishing: "Enviando o que você fez…",
  processing: (name: string) => `${name} está anotando a tarefa`,
  processingHint: "Leva um ou dois minutos. Pode fechar esta janela.",
  done: "A tarefa está pronta",
  doneHint: "Revise no painel e ligue.",
  review: "Revisar a tarefa",
  failed: "Não deu certo",
  again: "Ensinar de novo",
  openPanel: "Abrir painel",
  disconnect: "Desconectar",
  micTitle: "Deixe eu te ouvir",
  micBody: "O Chrome vai pedir para usar seu microfone. Sua voz só é gravada enquanto você ensina, e é apagada depois de virar texto.",
  micAllow: "Permitir microfone",
  micDone: "Microfone pronto. Volte para a extensão e aperte Começar a gravar.",
  micBlocked: "O microfone está bloqueado. Clique no ícone à direita da barra de endereço, permita o microfone e tente de novo.",
  micNeeded: "Permita o microfone primeiro. Abri uma aba para pedir.",
  pillRecording: (name: string) => `Gravando para ${name}`,
  pillPaused: (name: string) => `Pausado · ensinando ${name}`,
  pillShow: "Mostrar controles da gravação",
  pillHide: "Esconder controles da gravação",
  errors: {
    invalid_code: "Esse código não funcionou. Códigos valem 10 minutos: pegue um novo no painel.",
    invalid_server: "Esse endereço de painel não parece certo.",
    offline: "Não consegui falar com o painel. Confira o endereço e sua conexão.",
    unauthorized: "Este navegador foi desconectado. Conecte de novo.",
    agent_not_found: "Esse agente não é seu ou não existe mais.",
    mic_denied: "O microfone está bloqueado. Permita, ou desligue “Gravar minha voz”.",
    mic_missing: "Nenhum microfone encontrado. Conecte um, ou desligue “Gravar minha voz”.",
    mic_failed: "O microfone não ligou. Tente de novo, ou desligue “Gravar minha voz”.",
    audio_upload_failed: "Parte da sua voz não chegou ao painel. Os passos foram guardados.",
    recipe_failed: "Seu agente não conseguiu transformar isso numa tarefa. Veja o motivo no painel.",
    too_many_requests: "Tentativas demais. Espere um pouco e tente de novo.",
    busy: "Já tem uma gravação rodando.",
    unknown: "Algo deu errado. Tente de novo.",
  },
};

export type Copy = typeof en;

export function copyFor(language: string): Copy {
  return language.toLowerCase().startsWith("pt") ? ptBR : en;
}

export const copy = copyFor(typeof navigator === "undefined" ? "en" : navigator.language);

export function errorText(code: string | null | undefined, text: Copy = copy) {
  if (!code) return "";
  return text.errors[code] ?? text.errors.unknown;
}
